[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[colors.cursor]
cursor = "0x839496"
text = "0x002b36"

[colors.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0x002b36"
foreground = "0x839496"

[font]
size = 11

[font.normal]
family = "Sauce Code Pro Nerd Font"

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

# The default behaviour of shift + insert is to paste the primary
# selection clipboard which is NOT the normal clipboard.
# The Paste action of alacritty uses the normal clipboard
[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "Paste"

[window]
startup_mode = "Maximized"
